"""Unit tests for app.handler.embeddings.encoder.BertModel.

Covers both encoder variants via the tiny fixtures generated by
scripts/generate_tiny_bert_fixture.py and scripts/generate_tiny_nomic_fixture.py:

- tiny_bert: vanilla BERT (absolute position + GeLU MLP + token_type_ids).
- tiny_nomic: nomic-bert (rotary position + SwiGLU MLP, no token_type_ids).
"""
import json
from pathlib import Path

import mlx.core as mx
import pytest
from safetensors.numpy import load_file

from app.handler.embeddings.encoder import BertConfig, BertModel

FIXTURES = Path(__file__).resolve().parent / "fixtures"


def _load_fixture(name: str) -> tuple[BertModel, BertConfig]:
    fixture = FIXTURES / name
    cfg = BertConfig.from_dict(json.loads((fixture / "config.json").read_text()))
    weights = load_file(str(fixture / "model.safetensors"))
    model = BertModel(cfg)
    model.load_weights(
        [(k, mx.array(v)) for k, v in weights.items()],
        strict=False,
    )
    return model, cfg


@pytest.fixture
def bert_model():
    return _load_fixture("tiny_bert")


@pytest.fixture
def nomic_model():
    return _load_fixture("tiny_nomic")


def test_vanilla_bert_forward_returns_correct_shape(bert_model):
    """Vanilla BERT (absolute + gelu + token_type_ids) forwards a 5-token batch."""
    model, cfg = bert_model
    input_ids = mx.array([[1, 2, 3, 4, 0]])
    token_type_ids = mx.array([[0, 0, 0, 0, 0]])
    attention_mask = mx.array([[1, 1, 1, 1, 0]])
    out = model(input_ids, token_type_ids, attention_mask)
    assert out.shape == (1, 5, cfg.hidden_size)


def test_nomic_style_forward_returns_correct_shape(nomic_model):
    """Nomic-bert (rotary + swiglu, no type ids) forwards with token_type_ids=None."""
    model, cfg = nomic_model
    input_ids = mx.array([[1, 2, 3, 4, 0]])
    attention_mask = mx.array([[1, 1, 1, 1, 0]])
    out = model(input_ids, None, attention_mask)
    assert out.shape == (1, 5, cfg.hidden_size)


def test_nomic_uses_rope_not_absolute_position(nomic_model):
    """The SAME token at DIFFERENT absolute positions must yield different outputs.

    To isolate position-sensitivity from token-identity we feed the same trailing
    sequence `[7, 8]` once at positions 2-3 (after two padding tokens) and once
    at positions 0-1 (no padding). Under correct RoPE, the trailing tokens see
    different rotations and the resulting hidden states must differ. Under a
    broken implementation that ignores position (or zeros it out), the trailing
    outputs would match.
    """
    model, _ = nomic_model
    padded = mx.array([[0, 0, 7, 8]])
    unpadded = mx.array([[7, 8, 0, 0]])
    # Attend to ALL positions in both cases — we want pure position effect,
    # not attention-mask differences.
    mask = mx.array([[1, 1, 1, 1]])
    out_padded = model(padded, None, mask)
    out_unpadded = model(unpadded, None, mask)
    # Compare ONLY the trailing-token outputs: positions 2-3 in `padded` vs
    # positions 0-1 in `unpadded`. Same tokens, different absolute positions.
    trail_padded = out_padded[:, 2:4, :]
    trail_unpadded = out_unpadded[:, 0:2, :]
    assert not mx.allclose(trail_padded, trail_unpadded, atol=1e-4).item()


def test_vanilla_bert_position_sensitive(bert_model):
    """Absolute-position BERT must yield different outputs when same tokens
    appear at different positions.

    Mirrors the RoPE position-sensitivity test for the absolute-embedding
    code path: shifts the same `[7, 8]` pair between leading and trailing
    positions and verifies the per-token outputs differ. A bug that skipped
    the position-embedding addition would make these match.
    """
    model, _ = bert_model
    padded = mx.array([[0, 0, 7, 8]])
    unpadded = mx.array([[7, 8, 0, 0]])
    mask = mx.array([[1, 1, 1, 1]])
    ttids = mx.zeros_like(padded)
    out_padded = model(padded, ttids, mask)
    out_unpadded = model(unpadded, ttids, mask)
    trail_padded = out_padded[:, 2:4, :]
    trail_unpadded = out_unpadded[:, 0:2, :]
    assert not mx.allclose(trail_padded, trail_unpadded, atol=1e-4).item()
