"""Unit tests for app.handler.embeddings.loader.load_embedding_model.

Drives the loader from the on-disk tiny fixtures generated by
scripts/generate_tiny_bert_fixture.py and scripts/generate_tiny_nomic_fixture.py.
Also exercises the fail-loud config validator by mutating copies of those
fixtures into unsupported variants.
"""
import json
import shutil
import tempfile
from pathlib import Path

import pytest

from app.handler.embeddings.loader import (
    UnsupportedModelError,
    _remap_hf_to_internal,
    load_embedding_model,
)

FIXTURES = Path(__file__).resolve().parent / "fixtures"
BERT_FIXTURE = FIXTURES / "tiny_bert"
NOMIC_FIXTURE = FIXTURES / "tiny_nomic"


def test_loads_tiny_bert():
    """Vanilla BERT fixture loads with mean pooling and no matryoshka."""
    model, tokenizer, pooling_mode, matryoshka_dim = load_embedding_model(str(BERT_FIXTURE))
    assert model is not None
    assert tokenizer is not None
    assert pooling_mode == "mean"
    assert matryoshka_dim is None


def test_loads_tiny_nomic():
    """Nomic-style RoPE+SwiGLU fixture loads — covers SUPPORTED non-default variant."""
    model, tokenizer, pooling_mode, matryoshka_dim = load_embedding_model(str(NOMIC_FIXTURE))
    assert model is not None
    assert tokenizer is not None
    assert pooling_mode == "mean"


def _copy_fixture(src: Path, dst: Path) -> None:
    """Copy a fixture directory into dst (which must already exist or be empty)."""
    shutil.copytree(src, dst, dirs_exist_ok=True)


def test_unsupported_activation_errors():
    """An unrecognized hidden_act value must raise with a clear message."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        _copy_fixture(BERT_FIXTURE, tmp_dir)
        cfg_path = tmp_dir / "config.json"
        cfg = json.loads(cfg_path.read_text())
        cfg["hidden_act"] = "gelu_new"
        cfg_path.write_text(json.dumps(cfg))
        with pytest.raises(UnsupportedModelError, match="hidden_act='gelu_new'"):
            load_embedding_model(str(tmp_dir))


def test_unsupported_position_embedding_errors():
    """An unrecognized position_embedding_type value must raise with a clear message."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        _copy_fixture(BERT_FIXTURE, tmp_dir)
        cfg_path = tmp_dir / "config.json"
        cfg = json.loads(cfg_path.read_text())
        cfg["position_embedding_type"] = "alibi"
        cfg_path.write_text(json.dumps(cfg))
        with pytest.raises(UnsupportedModelError, match="position_embedding_type='alibi'"):
            load_embedding_model(str(tmp_dir))


def test_swiglu_and_rotary_are_supported():
    """tiny_nomic uses both swiglu + rotary; loader must accept them without raising."""
    model, _, _, _ = load_embedding_model(str(NOMIC_FIXTURE))
    assert model is not None


def test_matryoshka_dim_from_config_json():
    """matryoshka_dim declared in config.json is returned as-is."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        _copy_fixture(BERT_FIXTURE, tmp_dir)
        cfg_path = tmp_dir / "config.json"
        cfg = json.loads(cfg_path.read_text())
        cfg["matryoshka_dim"] = 16
        cfg_path.write_text(json.dumps(cfg))
        _, _, _, matryoshka_dim = load_embedding_model(str(tmp_dir))
        assert matryoshka_dim == 16


def test_matryoshka_dim_from_2_matryoshka_dir():
    """matryoshka_dim declared in 2_Matryoshka/config.json is picked up."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        _copy_fixture(BERT_FIXTURE, tmp_dir)
        mat_dir = tmp_dir / "2_Matryoshka"
        mat_dir.mkdir()
        (mat_dir / "config.json").write_text(json.dumps({"matryoshka_dim": 16}))
        _, _, _, matryoshka_dim = load_embedding_model(str(tmp_dir))
        assert matryoshka_dim == 16


def test_pooling_mode_defaults_to_cls_when_no_1_pooling_dir():
    """Plain BERT without a 1_Pooling/config.json defaults to cls."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        _copy_fixture(BERT_FIXTURE, tmp_dir)
        shutil.rmtree(tmp_dir / "1_Pooling")
        _, _, pooling_mode, _ = load_embedding_model(str(tmp_dir))
        assert pooling_mode == "cls"


# ----- HF -> internal key remap unit tests -----


def test_remap_strips_model_prefix():
    """`model.xxx` keys get the leading prefix stripped."""
    out = _remap_hf_to_internal({"model.embeddings.word_embeddings.weight": "v"})
    assert "embeddings.word_embeddings.weight" in out
    assert "model.embeddings.word_embeddings.weight" not in out


def test_remap_renames_layers_to_layer():
    """`encoder.layers.N.` becomes `encoder.layer.N.` (HF-singular convention)."""
    out = _remap_hf_to_internal({"encoder.layers.0.attention.output.dense.weight": "v"})
    assert "encoder.layer.0.attention.output.dense.weight" in out


def test_remap_splits_nomic_combined_qkv():
    """`attn.Wqkv` weight splits into separate q/k/v matrices.

    Nomic-bert ships a single combined `attn.Wqkv` Linear of shape (3H, H).
    We split it into three separate Q, K, V tensors of shape (H, H) each.
    """
    import numpy as np

    H = 8
    combined = np.arange(3 * H * H, dtype=np.float32).reshape(3 * H, H)
    out = _remap_hf_to_internal(
        {"encoder.layer.0.attn.Wqkv.weight": combined},
    )
    # Expected three keys:
    assert "encoder.layer.0.attention.self.query.weight" in out
    assert "encoder.layer.0.attention.self.key.weight" in out
    assert "encoder.layer.0.attention.self.value.weight" in out
    # Each has shape (H, H)
    for k in (
        "encoder.layer.0.attention.self.query.weight",
        "encoder.layer.0.attention.self.key.weight",
        "encoder.layer.0.attention.self.value.weight",
    ):
        assert out[k].shape == (H, H)
    # And the first H rows of combined are the query
    np.testing.assert_array_equal(out["encoder.layer.0.attention.self.query.weight"], combined[:H])
    np.testing.assert_array_equal(
        out["encoder.layer.0.attention.self.key.weight"], combined[H : 2 * H]
    )
    np.testing.assert_array_equal(
        out["encoder.layer.0.attention.self.value.weight"], combined[2 * H :]
    )
