"""Unit tests for app.handler.embeddings.encoder.BertModel.

Covers both encoder variants via the tiny fixtures generated by
scripts/generate_tiny_bert_fixture.py and scripts/generate_tiny_nomic_fixture.py:

- tiny_bert: vanilla BERT (absolute position + GeLU MLP + token_type_ids).
- tiny_nomic: nomic-bert (rotary position + SwiGLU MLP, no token_type_ids).
"""

import json
from pathlib import Path

import mlx.core as mx
import pytest
from safetensors.numpy import load_file

from app.handler.embeddings.encoder import BertConfig, BertModel

FIXTURES = Path(__file__).resolve().parent / "fixtures"


def _load_fixture(name: str) -> tuple[BertModel, BertConfig]:
    fixture = FIXTURES / name
    cfg = BertConfig.from_dict(json.loads((fixture / "config.json").read_text()))
    weights = load_file(str(fixture / "model.safetensors"))
    model = BertModel(cfg)
    model.load_weights(
        [(k, mx.array(v)) for k, v in weights.items()],
        strict=False,
    )
    return model, cfg


@pytest.fixture
def bert_model():
    return _load_fixture("tiny_bert")


@pytest.fixture
def nomic_model():
    return _load_fixture("tiny_nomic")


def test_vanilla_bert_forward_returns_correct_shape(bert_model):
    """Vanilla BERT (absolute + gelu + token_type_ids) forwards a 5-token batch."""
    model, cfg = bert_model
    input_ids = mx.array([[1, 2, 3, 4, 0]])
    token_type_ids = mx.array([[0, 0, 0, 0, 0]])
    attention_mask = mx.array([[1, 1, 1, 1, 0]])
    out = model(input_ids, token_type_ids, attention_mask)
    assert out.shape == (1, 5, cfg.hidden_size)


def test_nomic_style_forward_returns_correct_shape(nomic_model):
    """Nomic-bert (rotary + swiglu, no type ids) forwards with token_type_ids=None."""
    model, cfg = nomic_model
    input_ids = mx.array([[1, 2, 3, 4, 0]])
    attention_mask = mx.array([[1, 1, 1, 1, 0]])
    out = model(input_ids, None, attention_mask)
    assert out.shape == (1, 5, cfg.hidden_size)


def test_nomic_uses_rope_not_absolute_position(nomic_model):
    """The SAME token at DIFFERENT absolute positions must yield different outputs.

    To isolate position-sensitivity from token-identity we feed the same trailing
    sequence `[7, 8]` once at positions 2-3 (after two padding tokens) and once
    at positions 0-1 (no padding). Under correct RoPE, the trailing tokens see
    different rotations and the resulting hidden states must differ. Under a
    broken implementation that ignores position (or zeros it out), the trailing
    outputs would match.
    """
    model, _ = nomic_model
    padded = mx.array([[0, 0, 7, 8]])
    unpadded = mx.array([[7, 8, 0, 0]])
    # Attend to ALL positions in both cases — we want pure position effect,
    # not attention-mask differences.
    mask = mx.array([[1, 1, 1, 1]])
    out_padded = model(padded, None, mask)
    out_unpadded = model(unpadded, None, mask)
    # Compare ONLY the trailing-token outputs: positions 2-3 in `padded` vs
    # positions 0-1 in `unpadded`. Same tokens, different absolute positions.
    trail_padded = out_padded[:, 2:4, :]
    trail_unpadded = out_unpadded[:, 0:2, :]
    assert not mx.allclose(trail_padded, trail_unpadded, atol=1e-4).item()


def test_vanilla_bert_position_sensitive(bert_model):
    """Absolute-position BERT must yield different outputs when same tokens
    appear at different positions.

    Mirrors the RoPE position-sensitivity test for the absolute-embedding
    code path: shifts the same `[7, 8]` pair between leading and trailing
    positions and verifies the per-token outputs differ. A bug that skipped
    the position-embedding addition would make these match.
    """
    model, _ = bert_model
    padded = mx.array([[0, 0, 7, 8]])
    unpadded = mx.array([[7, 8, 0, 0]])
    mask = mx.array([[1, 1, 1, 1]])
    ttids = mx.zeros_like(padded)
    out_padded = model(padded, ttids, mask)
    out_unpadded = model(unpadded, ttids, mask)
    trail_padded = out_padded[:, 2:4, :]
    trail_unpadded = out_unpadded[:, 0:2, :]
    assert not mx.allclose(trail_padded, trail_unpadded, atol=1e-4).item()


# ---------------------------------------------------------------------------
# qkv_proj_bias regression tests (added after the nomic correctness bug)
# ---------------------------------------------------------------------------


def _enumerate_param_keys(model) -> list[str]:
    """Walk model.parameters() and return every leaf path."""
    keys: list[str] = []

    def walk(prefix: str, p) -> None:
        if hasattr(p, "items"):
            for k, v in p.items():
                walk(f"{prefix}.{k}" if prefix else k, v)
        elif isinstance(p, list):
            for i, v in enumerate(p):
                walk(f"{prefix}.{i}", v)
        else:
            keys.append(prefix)

    walk("", model.parameters())
    return keys


def test_bertconfig_default_qkv_proj_bias_is_true():
    """Vanilla BERT default behavior: attention projections carry biases."""
    cfg = BertConfig(
        hidden_size=8,
        num_hidden_layers=1,
        num_attention_heads=2,
        intermediate_size=16,
        vocab_size=10,
    )
    assert cfg.qkv_proj_bias is True


def test_bertconfig_from_dict_reads_qkv_proj_bias_false():
    """Nomic-bert sets qkv_proj_bias=false in its config; the dataclass must
    pick it up via BertConfig.from_dict so the encoder can build bias-free
    attention projections.
    """
    cfg = BertConfig.from_dict(
        {
            "hidden_size": 8,
            "num_hidden_layers": 1,
            "num_attention_heads": 2,
            "intermediate_size": 16,
            "vocab_size": 10,
            "qkv_proj_bias": False,
        }
    )
    assert cfg.qkv_proj_bias is False


def _projection_bias_keys(model) -> list[str]:
    """Return Q/K/V/output-dense bias parameter paths from a BertModel.

    LayerNorm biases (`attention.output.LayerNorm.bias`) are unrelated to
    `qkv_proj_bias` — every LayerNorm has its own bias regardless — so
    they're excluded here. Only the four attention Linear projections are
    counted.
    """
    keys = _enumerate_param_keys(model)
    return sorted(k for k in keys if ".attention." in k and k.endswith(".bias") and ".LayerNorm." not in k)


def test_qkv_proj_bias_false_drops_attention_bias_params():
    """When qkv_proj_bias=False, BertModel must not allocate any
    attention-projection bias parameter. Otherwise safetensors that omit
    the bias keys (nomic-bert) load with strict=False and leave
    random-init biases in place — silently producing semantically wrong
    embeddings (the original v0.1.x bug, mean cosine 0.18 vs ref >=0.999).
    """
    cfg = BertConfig(
        hidden_size=8,
        num_hidden_layers=2,
        num_attention_heads=2,
        intermediate_size=16,
        vocab_size=10,
        qkv_proj_bias=False,
    )
    model = BertModel(cfg)
    keys = _projection_bias_keys(model)
    assert keys == [], f"qkv_proj_bias=False must remove all attention projection biases; got {keys}"


def test_qkv_proj_bias_true_keeps_attention_bias_params():
    """Default vanilla-BERT path must allocate the four projection biases
    per layer (Q, K, V, and the attention output dense). Regression guard
    so the nomic fix doesn't accidentally strip biases from models that
    actually have them (mxbai, BGE, etc).
    """
    cfg = BertConfig(
        hidden_size=8,
        num_hidden_layers=2,
        num_attention_heads=2,
        intermediate_size=16,
        vocab_size=10,
        qkv_proj_bias=True,
    )
    model = BertModel(cfg)
    keys = _projection_bias_keys(model)
    # Per layer: query.bias, key.bias, value.bias, attention.output.dense.bias.
    assert len(keys) == cfg.num_hidden_layers * 4, f"expected 4 attention projection biases per layer, got {keys}"
