"""Unit tests for app.handler.embeddings.encoder.BertModel.

Covers both encoder variants via the tiny fixtures generated by
scripts/generate_tiny_bert_fixture.py and scripts/generate_tiny_nomic_fixture.py:

- tiny_bert: vanilla BERT (absolute position + GeLU MLP + token_type_ids).
- tiny_nomic: nomic-bert (rotary position + SwiGLU MLP, no token_type_ids).
"""
import json
from pathlib import Path

import mlx.core as mx
import pytest
from safetensors.numpy import load_file

from app.handler.embeddings.encoder import BertConfig, BertModel

FIXTURES = Path(__file__).resolve().parent / "fixtures"


def _load_fixture(name: str) -> tuple[BertModel, BertConfig]:
    fixture = FIXTURES / name
    cfg = BertConfig.from_dict(json.loads((fixture / "config.json").read_text()))
    weights = load_file(str(fixture / "model.safetensors"))
    model = BertModel(cfg)
    model.load_weights(
        [(k, mx.array(v)) for k, v in weights.items()],
        strict=False,
    )
    return model, cfg


@pytest.fixture
def bert_model():
    return _load_fixture("tiny_bert")


@pytest.fixture
def nomic_model():
    return _load_fixture("tiny_nomic")


def test_vanilla_bert_forward_returns_correct_shape(bert_model):
    """Vanilla BERT (absolute + gelu + token_type_ids) forwards a 5-token batch."""
    model, cfg = bert_model
    input_ids = mx.array([[1, 2, 3, 4, 0]])
    token_type_ids = mx.array([[0, 0, 0, 0, 0]])
    attention_mask = mx.array([[1, 1, 1, 1, 0]])
    out = model(input_ids, token_type_ids, attention_mask)
    assert out.shape == (1, 5, cfg.hidden_size)


def test_nomic_style_forward_returns_correct_shape(nomic_model):
    """Nomic-bert (rotary + swiglu, no type ids) forwards with token_type_ids=None."""
    model, cfg = nomic_model
    input_ids = mx.array([[1, 2, 3, 4, 0]])
    attention_mask = mx.array([[1, 1, 1, 1, 0]])
    out = model(input_ids, None, attention_mask)
    assert out.shape == (1, 5, cfg.hidden_size)


def test_nomic_uses_rope_not_absolute_position(nomic_model):
    """Position-shifted inputs must produce *different* outputs under RoPE.

    Same token IDs at different absolute positions exercise RoPE: if our
    implementation accidentally ignored positions (or applied position 0 to
    everything), the two outputs would match. They must not.
    """
    model, _ = nomic_model
    a = mx.array([[1, 2, 3, 4]])
    b = mx.array([[0, 1, 2, 3]])  # same trailing tokens, different positions
    mask = mx.array([[1, 1, 1, 1]])
    out_a = model(a, None, mask)
    out_b = model(b, None, mask)
    assert not mx.allclose(out_a, out_b, atol=1e-4).item()


def test_vanilla_bert_is_deterministic(bert_model):
    """Identical input and identical positions yields bitwise-equal output."""
    model, _ = bert_model
    a = mx.array([[5, 5, 5, 5]])
    mask = mx.array([[1, 1, 1, 1]])
    ttids = mx.zeros_like(a)
    out_a = model(a, ttids, mask)
    out_b = model(a, ttids, mask)
    assert mx.allclose(out_a, out_b, atol=1e-6).item()
